### ISSUE TITLE
Broken layout in High DPI windows

### ISSUE THREAD

**Issue by Jessidhia** [marzent/IINACT#10]
![image](https://user-images.githubusercontent.com/73085/190376435-4bed216e-de20-4161-9709-cf347b0dcf4a.png)

The layout issues are mostly just ugly ("Parse Settings" looks like a crushed menu bar, both "Parse Settings" and "Debug Log" are clipping the descenders on "g", checkboxes don't look like checkboxes, combobox triangle is misaligned) but the "Changing Parsing Settings may require an application restart" label is blocking access to the Game Language combobox.

Windows is 22H2 with 200% scale.

**Comment by nopjmp** [comment]
You might be able to workaround this via the DPI compatibility options when you look at the IINACT.exe properties -> compatibility and play around with that. Winforms historically are not the best thing when it comes to hidpi scaling.

**Comment by marzent** [comment]
Adding to that, I did actually experiment a bit with different DPI inside the VS designer, and it seemed to go completely haywire with most things anchored to the right.
Dunno if this is feasible to fix; long term a better UI solution should definitely be implemented (maybe dear ImGui xD)

**Comment by marzent** [comment]
IINACT no longer uses WinForms and should scale properly now
