### ISSUE TITLE
Fights show starting at default epoch time when live logging with FFLogs Uploader (Overwolf + Original)

### ISSUE THREAD

**Issue by lennalefay** [marzent/IINACT#109]
**Issue:** Combat data for fights logs with a start date of 12/31/1969 and end date of the proper time when using the Overwolf FFLogs Uploader and live logging. Logs were showing as recording 55 years of time. (Please see below: I could not replicate this with ACT so I submitted it here, though I have also reported this error to FFLogs staff.)

**Can Replicate:** Yes, by live logging combat with IINACT logs from two different devices.

**Notes:**
* All PCs and IINACT/FFXIV setups were set to the correct time.
* All logs had proper times in them and otherwise looked properly formatted.
* This has been reported by other users in the FFLogs Discord channel.
* Submitting this here because both versions of the FFLogs Uploader had this issue, and uploading the logs after combat (to either uploader) does not replicate the issue and works properly. Using live logging in either uploader with desktop ACT does not replicate this issue and works properly.
* Also submitted this issue to FFLogs/Archon.gg for consistency.
* Both IINACT versions tested were on PCs running Windows 11 version 23H2 on MST time zone.
* To the best of my knowledge, all versions of Windows, FFLogs Uploaders, ACT, FFXIVLauncher/Dalamud, and IINACT were fully updated at the time.
* I had proper working Live Logging two weeks ago on both devices; nothing notable was changed on either device since then.

I am away from my PC at the moment but can upload the logs that errored in 2-3 hours, though even creating new logs seemed to produce the same issue. Please let me know if there's anything else you need from me in order to facilitate looking into this.

**Comment by jasonrm** [comment]
Did a quick check of my logs, and while they live logged just fine, I do see this one line during init 

```
256|2024-08-18T18:50:18.3618665-07:00|274|OverlayPlugin|ActorControlSelfExtra|1|189dc820365a61f6
260|1970-01-02T11:43:38.0000000-07:00|0|0|1|1|bd4895cba0fa2a22
42|2024-08-18T18:51:35.5230000-07:00|1320729D||0|0|0|f1db00338279e443
```

Which gets picked up by the FFLogs uploader and turns the duration into uh,
<img width="161" alt="Screenshot 2024-08-19 at 05 20 13" src="https://github.com/user-attachments/assets/fe3e7fd0-f74a-44fd-8cdc-e38c81a020f4">

Oldest report I have with that issue is from August 9. All the fights themselves have the right dates/times, but it's tricking the FF Logs uploader into thinking the overall report was started at epoch.

I'll see if the FF Logs uploader can be less silly. 😅

**Comment by marzent** [comment]
Ah this makes a bit more sense then, personally didn't see that issue happening yet.
The timestamps are now exclusively fed from a network packet hook, but this also means that at least one packet needs to have been processed before the first logline is emitted, leaving a tiny window for OverlayPlugin to emit a logline with the unix epoch (but not the actual network based loglines from FFXIV_ACT_Plugin)...

**Comment by marzent** [comment]
Fixed with https://github.com/marzent/IINACT/commit/19502f474bb1f251930e726b64a685deeab87b88
