### ISSUE TITLE
about PublishSingleFile

### ISSUE THREAD

**Issue by tssailzz8** [marzent/IINACT#13]
i find if i hava <PublishSingleFile>true</PublishSingleFile>,i can not debug it.
i don't konw what the difference between them
https://github.com/marzent/IINACT/blob/d836a4a34352bcdda9df3deedc8ce8df998598f7/IINACT/IINACT.csproj#L12

**Comment by marzent** [comment]
To attach to a single-file published IINACT (or any dotnet application really), you need to copy mscordbi.dll from the win-x64 directory into the exe directory.
