### ISSUE TITLE
in china

### ISSUE THREAD

**Issue by tssailzz8** [marzent/IINACT#14]
if we use this https://github.com/TundraWork/FFXIV_ACT_Plugin_CN/releases and pack one exe.it has a error
FFXIV_ACT_Plugin: Unexpected error trying to read network data.  Please restart ACT.  System.NotSupportedException: CodeBase is not supported on assemblies loaded from a single-file bundle.    at System.Reflection.RuntimeAssembly.get_CodeBase()    at Machina.FFXIV.Oodle.OodleFactory.AutoChooseImplementation(OodleImplementation implementation, String path)    at Machina.FFXIV.FFXIVNetworkMonitor.Start()    at FFXIV_ACT_Plugin.Network.ScanPackets.StartScan()

**Comment by marzent** [comment]
It seems the custom Machina version bundled by the CN plugin is trying to resolve the assembly location. As the exception said, CodeBase is not compatible with single file; however you can use AppDomain for basically the same result like here https://github.com/marzent/IINACT/blob/d836a4a34352bcdda9df3deedc8ce8df998598f7/FetchDependencies/FetchDependencies.cs#L9

So your options are either to 
* Not publish as single-file
* Patch the IL there with Cecil to use an implementation similar to IINACT if you want it fully automated
* Or ask the developers of the CN FFXIV ACT plugin to provide you with a build that does not use CodeBase (if that is not possible dnSpy should be able to quickly patch it up as well)

**Comment by marzent** [comment]
Actually the Machina used by the CN version can be found here https://github.com/TundraWork/machina

If you submodule it instead, you can directly import the project reference and make the necessary changes quite easily

**Comment by tssailzz8** [comment]
> 其实 CN 版使用的 Machina 可以在这里找到https://github.com/TundraWork/machina
> 
> 如果您改为子模块，则可以直接导入项目引用并轻松进行必要的更改

it too old

**Comment by marzent** [comment]
Hm maybe you can ask them kindly to provide a newer source (which they should since Machina is GPLv3)

**Comment by tssailzz8** [comment]
can i load local op? i use https://quisquous.github.io/cactbot/ui/radar/Radar.html?OVERLAY_WS=ws://127.0.0.1:10501/ws,it is 404
![image](https://user-images.githubusercontent.com/52206101/191789379-c53ce5e1-9a78-474e-bbda-67475b913e1c.png)

**Comment by TundraWork** [comment]
Hi there, we are happy to provide help with your issues.
I have updated https://github.com/TundraWork/machina repo to reflex the newest codebase of our Machina version.
We used our own toolchain to automatically patch FFXIV_ACT_Plugin, unfortunately, we can not provide source code for our patching toolchain. But we're very happy to provide technical details about our modifications for FFXIV_ACT_Plugin. If you are interested, you can reach us at https://discord.gg/KYbkUnU .

**Comment by marzent** [comment]
Thanks a lot for the info!
Will be closing this issue as the machina crash itself got fixed
