### ISSUE TITLE
about cactbot config

### ISSUE THREAD

**Issue by tssailzz8** [marzent/IINACT#15]
i want to change my cactbot config,how can i do it

**Comment by Dormanil** [comment]
Open the [cactbot config website](https://quisquous.github.io/cactbot/ui/config/config.html?OVERLAY_WS=ws://127.0.0.1:10501/ws), in Firefox or as an overlay ingame, and change your preferences to your hearts content. If you use customisations for timelines and other alerts, you need to set your `Cactbot user directory` to the folder where you expect to put those customisations.
