### ISSUE TITLE
about OverlayPlugin

### ISSUE THREAD

**Issue by tssailzz8** [marzent/IINACT#16]
i think we should updata OverlayPlugin to https://github.com/OverlayPlugin/OverlayPlugin

**Comment by marzent** [comment]
When IINACT was created (and actually up until v2.0), the original ngld fork was abandoned for months (and didn't even properly build), hence the manual modifications.

I agree it would be cleaner to submodule that updated fork instead and keep the differences as small as possible.

**Comment by marzent** [comment]
We are now up to date with https://github.com/OverlayPlugin/OverlayPlugin from a functional point of view, will try to reduce the difference between IINACTs version and theirs as much as possible, i.e. with https://github.com/OverlayPlugin/OverlayPlugin/pull/82 and hopefully rebase soon.
