### ISSUE TITLE
Tracking of P8S p1 Clones as player entities

### ISSUE THREAD

**Issue by sleepylinde** [marzent/IINACT#17]
One of the clones during P8S part one get registered as player damage and push the overlay into 24 man mode. Is this an IINACT issue or rather the overlay I'm using?

Using MopiMopi with Browsingway.

Edit: This happens during Gorgon 2. When the clone defeats 2 of the snakes.

**Comment by marzent** [comment]
The Combat data passed to Overlay there comes straight from OverlayPlugin and how it is displayed depends entirely on the Overlay...

Having said that there has been some additional filtering added to upstream OverlayPlugin which has now also been integrated into IINACT (if this will resolve your issue however, I cannot say; if it doesn't it is probably best to open an issue with the respective Overlay)
