### ISSUE TITLE
Unable to set different zoom level for cactbot alerts and timeline

### ISSUE THREAD

**Issue by fly1n** [marzent/IINACT#21]
https://quisquous.github.io/cactbot/ui/raidboss/raidboss_alerts_only.html and https://quisquous.github.io/cactbot/ui/raidboss/raidboss_timeline_only.html both redirect to 
https://quisquous.github.io/cactbot/ui/raidboss/raidboss.html?timeline=x&alerts=y.
Currently it is impossible to set different zoom level for them.

**Comment by marzent** [comment]
That it is a limitation of CEF (or whatever chromium based solution you use to display overlays (see https://magpcss.org/ceforum/viewtopic.php?f=6&t=15167&start=10)) and doesn't really have anything to do with IINACT...

It would probably be best to raise an issue with whatever renders your overlay
