### ISSUE TITLE
IINACT needs to launch before logging in. 

### ISSUE THREAD

**Issue by seivan** [marzent/IINACT#28]
>  ACT MUST be started before you log into FFXIV, or the plugin cannot decode the network traffic at all, regardless of vpn / npcap / raw socket support. 

![image](https://user-images.githubusercontent.com/55424/211796222-29215c3f-6ac7-4c09-9bfe-65699f21a46d.jpeg)

Right not the "Auto start IINACT" launches after auth, but it might have to launch before. 
That's not a huge problem as you can manually launch it before, but it does break the "auto launch" functionality of it.

**Comment by marzent** [comment]
Login here means selecting your character at the main menu and not SEs OAuth, so everything is still fine
