### ISSUE TITLE
Fails to launch on Arch Linux

### ISSUE THREAD

**Issue by Sharparam** [marzent/IINACT#3]
Not sure if I'm maybe missing something in how it's supposed to be started, in that case please tell me!

Downloading the pre-built version with bundled everything from releases (https://github.com/marzent/IINACT/releases/download/v0.1.0/IINACT.zip), and starting it with the following command:

```sh
WINEPREFIX=~/.xlcore/wineprefix WINEESYNC=1 WINEFSYNC=1 ~/.xlcore/compatibilitytool/beta/lutris-GE-Proton7-23-x86_64/bin/wine64 ~/.xlcore/wineprefix/drive_c/IINACT/IINACT.exe
```

It outputs the following:

```
Failure processing application bundle.
Failed to create directory [C:\/home/sharparam/.cache/dotnet_bundle_extract\] for extracting bundled files.
067c:fixme:advapi:RegisterEventSourceW ((null),L".NET Runtime"): stub
067c:fixme:advapi:ReportEventW (00000000CAFE4242,0x0001,0x0000,0x000003ff,0000000000000000,0x0001,0x00000000,000000000019FDD0,0000000000000000): stub
067c:err:eventlog:ReportEventW L"Description: A .NET application failed.\nApplication: IINACT.exe\nPath: C:\\IINACT\\IINACT.exe\nMessage: Failure processing application bundle.\nFailed to create directory [C:\\/home/sharparam/.cache/dotnet_bundle_extract\\] for extracting bundled files.\n\n"
067c:fixme:advapi:DeregisterEventSource (00000000CAFE4242) stub
```

It seems to be trying to mix Linux and Windows paths?

[Full output when running with `WINEDEBUG=warn+all`](https://gist.github.com/Sharparam/8bb73ff01e5ba0e07a50537292b351ad)

## Details

Running it in the wine prefix created by XIVLauncher.Core, using [wine-ge-custom 7.23](https://github.com/GloriousEggroll/wine-ge-custom/releases/tag/GE-Proton7-23) as the runner.

**Comment by marzent** [comment]
This is because wine is inheriting environment variables from your linux dotnet6 install (in this case `DOTNET_BUNDLE_EXTRACT_BASE_DIR`). 

You can either unset it before launching wine, or alternatively write a `.bat` that sets it to a sane windows style directory and then launches the exe. 

That is not really something that can be alleviated by IINACT but is just how the self contained runtime behaves.

**Comment by Sharparam** [comment]
That indeed makes it launch, thanks for the info!

**Comment by Sancoraa** [comment]
> That indeed makes it launch, thanks for the info!

How did you actually make this ? I have a same problem and have no idea how to unset the environment variables, thanks for any help !

**Comment by teozkr** [comment]
@Sancoraa `export DOTNET_BUNDLE_EXTRACT_BASE_DIR=`

**Comment by Sharparam** [comment]
@Sancoraa For reference, this is the script I use to launch IINACT: https://gist.github.com/Sharparam/788128a645f875cc236c3d3a4a942f33

I switched to using an explicit path for the extract dir instead of just blank.

(I'm not currently using the xiv/act options in it, everything also uses hardcoded paths so could definitely be improved)

**Comment by Sharparam** [comment]
@RainerZufahl Try launching the game before IINACT, that's what I do. Maybe there's some missing env var or something that messes up the wine stuff for the game if IINACT launches first.
