### ISSUE TITLE
Cactbot Raidboss overlays identical

### ISSUE THREAD

**Issue by NCC-Lykos** [marzent/IINACT#30]
Not sure if intended, but running IINACT on Windows with Browsingway -- The URL for the 3 Cactbot Raidboss overlays are identical, always producing Timeline and Alerts instead of being able to split them up.

**Comment by frstndrd** [comment]
Yeah, that seems to be an issue. Combined alerts and timeline belong to `/cactbot/ui/raidboss/raidboss.html`, while alerts only would be `/cactbot/ui/raidboss/raidboss_alerts_only.html` and timeline only would be `/cactbot/ui/raidboss/raidboss_timeline_only.html`. Replacing that string before the .html does the trick.

**Comment by marzent** [comment]
Indeed this is an issues which stems from switching to https://github.com/cking/act-overlays as overlay preset source and IINACT currently not interpreting the additional options in there

**Comment by marzent** [comment]
this is fixed with this implementation https://github.com/marzent/IINACT/commit/f9af4c62c1e6947a85def7afbc2c6fd5630f2837
