### ISSUE TITLE
Instructions on where to find "external dependencies" folder on computer?

### ISSUE THREAD

**Issue by turtlehero** [marzent/IINACT#31]
i WANT to try this out. but i can't because i can't find this folder, if it requires me doing anything with github specifically i am not going to bother, i just want a place to dump the latest FFXIV parsing plugin version and it works, or better yet it grabs the latest one automatically

**Comment by cozyGalvinism** [comment]
IINACT will automatically download and create that folder on the first start.

**Comment by turtlehero** [comment]
ok. where is that folder located? documents? program files? appdata where????????

**Comment by cozyGalvinism** [comment]
Next to IINACT, it's called `external_dependencies`. You don't need to touch anything, IINACT will automatically download Machina and the ACT plugin and place them inside there.

If it doesn't create the folder, you are probably missing .NET 7 (if you use the non-self contained version).

**Comment by turtlehero** [comment]
if its already doing all that, the parsing does not work then when it works in ACT. guess i'll try it out in a year or 2 if its still alive. great concept i guess, not worth messing around with.

**Comment by cozyGalvinism** [comment]
Well, it works for us. See you in a year or two then.
