### ISSUE TITLE
Error: br0: You don't have permission to capture on that device (socket: Operation not permitted)

### ISSUE THREAD

**Issue by Megahaosguy** [marzent/IINACT#4]
Hello, I'm trying to use this software on Manjaro along with XIVLauncher. I have them both running under the same wine prefix but it seems there is some issue with permissions regarding monitoring my network adapter. Any help would be appreciated!

![image](https://user-images.githubusercontent.com/6866961/185768699-bb66e6c1-e4f8-4ff9-8fc9-511faac2cfb9.png)

**Comment by marzent** [comment]
This is usually because of missing capabilities of wine executables and/or having wine setup on a nosuid partition.
If you join the IINACT discord (https://discord.gg/gkaqrGrNe7), this will probably be easier to figure out...
