### ISSUE TITLE
Trojan in published archive

### ISSUE THREAD

**Issue by Airex** [marzent/IINACT#43]
![image](https://user-images.githubusercontent.com/302188/225318284-79bcc34b-1745-41e6-8712-3d84cdc1a3ec.png)

**Comment by marzent** [comment]
Indeed this is a duplicate of https://github.com/marzent/IINACT/issues/42

**Comment by Airex** [comment]
> This is a false positive and happens due to Deucalion DLL injections. See #42 for more infos.

if it is known issue, in this case, would be great to have this info available in initial README.md
thank you

**Comment by marzent** [comment]
I have pinned https://github.com/marzent/IINACT/issues/42 for now so it is easier to find.

This will be a non issue in the future as well when Deucalion is no longer being used.
