### ISSUE TITLE
Massive performance usage, with errors encountered during S rank fight.

### ISSUE THREAD

**Issue by iRobsie** [marzent/IINACT#50]
Had an S rank spawn, went to go join in on it and as soon as I showed up my FPS dipped into the single digits (extremely abnormal, only break under 60 fps when something breaks usually), and mid fight I pulled up my logs to see that IINACT was throwing errors. Was able to disable it mid fight and fps increased, but will post logs of the errors that occurred.

[dalamud.log](https://github.com/marzent/IINACT/files/11178226/dalamud.log)

**Comment by marzent** [comment]
I am not sure if the performance regression is directly caused by one of IINACTs components or rather just excessive logging of the collection modified ACT error...

Roughly how many errors per second were happening in the above log?

**Comment by marzent** [comment]
Anyways the three exceptions in the log above should no longer be possible with https://github.com/marzent/IINACT/commit/de890d89bf6de3a867568f1d0d9e280f3bcd53c9

**Comment by iRobsie** [comment]
Sorry for the late reply but I believe it may have been regression instead of logging, but alas I no longer have the log on hand (going off of memory).
If the problem happens again to a severe extent with only these relatable errors being shown in an understandable way, I'll report them but I'll mark as closed for now. Thank you!
