### ISSUE TITLE
Please let me request!

### ISSUE THREAD

**Issue by AngelSeed** [marzent/IINACT#51]
Please let me request!
INNACT is a wonderful thing.
thank you.

Asks to add a text command.
/i inact start
/i inact stop
I thought it would be convenient if there was a command that can be turned on and off like this, so please let me suggest it!
The reason is that command operation is convenient to use properly.
And humbly thank you.

**Comment by marzent** [comment]
I assume you want to start and stop the websocket server?

The current encounter can already be stopped with `/endenc`

**Comment by AngelSeed** [comment]
Current original Advanced Combat Tracker
There are many Pligins, so in order to use them properly,
Mainly Pligins such as training wheels.
If there is a command to start and stop the websocket server,
Changing TTS You can change anything with training wheels, etc., so you can use them according to your preference.
I thought it would be convenient to be able to use it properly.
Please consider it.

**Comment by marzent** [comment]
I can add web socket commands, it is not an issue :)

Concerning more TTS options there is integration with the Dalamud TTS plugin planned which will allow for much more TTS customisation in the future

**Comment by AngelSeed** [comment]
Thank you! !
It is saved that the update is early.
Please keep up the good work.
I apologize for the selfish request, but thank you in advance.

**Comment by marzent** [comment]
Should be added with https://github.com/marzent/IINACT/commit/4bd7d54f9fa8801bbc055b41106090d1a8ff769d.

Server can be started with  `/iinact start` and stopped with `/iinact stop`

**Comment by AngelSeed** [comment]
Thank you very much. I appreciate it
