### ISSUE TITLE
cact dps overlay uri issue

### ISSUE THREAD

**Issue by dalamudx** [marzent/IINACT#53]
should add '/' at the end of uri
env:
iinact+browsingway
for example:
wrong:http://proxy.iinact.com/overlay/horizoverlay/?HOST_PORT=ws://127.0.0.1:10501
correct:http://proxy.iinact.com/overlay/horizoverlay/?HOST_PORT=ws://127.0.0.1:10501/

**Comment by marzent** [comment]
Is there any example of it creating issues as it is currently?

@Orphis maybe you have some insights on this

**Comment by dalamudx** [comment]
@marzent ok
