### ISSUE TITLE
Domain safety issue: Skyline Overlay

### ISSUE THREAD

**Issue by dsrkafuu** [marzent/IINACT#55]
Please update the domain of Skyline Overlay at https://www.iinact.com/overlay/.
I no longer have ownership of this domain and it may be bought by someone redirected to an unsafe website. 😂
New address: https://skyline.dsrkafuu.net/

**Comment by marzent** [comment]
The overlays are internally pulled from https://github.com/cking/act-overlays, it should be fairly open to contributions I believe. 

The proxy part is being done by @FleetAdmiralButter, not sure if it would pick up the change automatically…

But thanks for the notice!

**Comment by marzent** [comment]
Should hopefully be good after https://github.com/cking/act-overlays/pull/3 and the proxy is updated

**Comment by FleetAdmiralButter** [comment]
I just checked and the overlay proxy has been using https://skyline.dsrkafuu.net/ all along. I must have made a typo on the website when putting together the table - it's been updated to reference the correct domain now.

**Comment by marzent** [comment]
fixed with https://github.com/marzent/IINACT/commit/9d0b2d5501f848302d173a072bad9e766f5e14cb
