### ISSUE TITLE
IINACT plugin missing stuff

### ISSUE THREAD

**Issue by LixueYukiharu** [marzent/IINACT#57]
The iinact dalamud plugin is missing a couple of elements in the configuration menu of the plugin. 
When selecting an overlay, it does not give me the url for me to put in browsingway
It does not show the WebSocket server area, so I cannot input the host server manually, and the buttons to stop or restart are also missing

I tried uninstalling and reinstalling the plugin and nothing has changed

![Capture](https://github.com/marzent/IINACT/assets/135276205/92e4a8ce-0912-4cdc-a6e6-66e7f54f26a9)

**Comment by LukeBrummett** [comment]
same issue here

**Comment by LukeBrummett** [comment]
Found a fix. Right click the plugin in the plugin installer and select the reload option. 
![image](https://github.com/marzent/IINACT/assets/47190575/07264189-1431-4a9f-b228-a3b298cf9555)

**Comment by LixueYukiharu** [comment]
That fixed it! Thank you
