### ISSUE TITLE
Status not saving when restarting the game

### ISSUE THREAD

**Issue by Zimmerson** [marzent/IINACT#64]
Hi,

I'm not sure this is really a bug - more probably as a feature request?

When choosing the URI Overlay, once you restart, it resets to Cactbot. Is there a way you could have it so the Overlay you choose is saved?

Thanks!

**Comment by marzent** [comment]
Fixed with https://github.com/marzent/IINACT/commit/fd9e7ae94c2621c2ac4cbdc12007c242b6e32a45
