### ISSUE TITLE
Since 2.4.0.1 update, parses not assigned to a zone

### ISSUE THREAD

**Issue by MadCabbit** [marzent/IINACT#69]
Ever since the last update, fflogs updated will see the instances for me to select, but when they are uploaded to fflogs, no fights are shown, and the logs all show as "Unknown zone".

**Comment by marzent** [comment]
Can you test 2.4.0.2 with a fresh log and see if it is fixed?

**Comment by MadCabbit** [comment]
Fflogs is now acknowledging the parse.  However, it's still showing up as "Unknown zone".  The previous log right before I updated to 2.4.0.1 still shows the primary zone when uploaded (that one being primarily Anabesios normal and savage with 1-2 expert dungeons and a Thaleia), and it's no longer doing this.

**Comment by MadCabbit** [comment]
hrm, I wonder if I just didn't notice that behavior before.  The first log for moggle mog still shows it, but my p12n kill log now shows Anabaseios, so maybe its just something fflogs is doing after processing a current log?

**Comment by marzent** [comment]
seems to be, 156f527c43bb2a2500f251f90e4d93aa5269dcd6 does fix the issue for me
