### ISSUE TITLE
The `URI` box does not save through restarts

### ISSUE THREAD

**Issue by Felanbird** [marzent/IINACT#70]
As noted in https://github.com/marzent/IINACT/issues/64, previously IINACT would revert to the default `Cactbot` on startup, despite what the user had most-recently selected.

This issue was resolved https://github.com/marzent/IINACT/commit/fd9e7ae94c2621c2ac4cbdc12007c242b6e32a45 but this is not the case for the `URI` box, it still reverts to the Cactbot link on startup.

Steps to Replicate:
1. Open IINACT settings
2. Select any option other than `Cactbot Configuration`
3. Close FFXIV
4. Re-open FFXIV
5. Open IINACT settings and see that the overlay correctly persisted, but the `URI` did not
![image](https://github.com/marzent/IINACT/assets/41973452/69e31a8a-62c0-4c53-88ab-a4b33c275ab4)

**Comment by marzent** [comment]
Should be fixed with https://github.com/marzent/IINACT/commit/5a4ca889183c3be30539a8f8fffe4c257f25bfd3
