### ISSUE TITLE
add option to save current logs to disk immediately without quitting?

### ISSUE THREAD

**Issue by jacob-keller** [marzent/IINACT#75]
IINACT can save lots to disk, but it appears to only rotate the log file and save it to disk when exiting FFXIV. It would be handy if there was a button or command I could use to immediately save logs to disk so I can access them and do things like upload without needing to close the game.

**Comment by marzent** [comment]
The log file is flushed to the disk every few seconds and should be up-to-date without needing to close the game.

Rotation is currently handled by the FFXIV_ACT_Plugin itself and is rather inflexible and I'd prefer not touching that if possible, just to keep changes to it to a minimum.

Maybe something else on the system was causing an old file to be read... Btw on which platform does this happen?

**Comment by jacob-keller** [comment]
Huh, I saw a log file but it had a size of zero for a while. However I just confirmed that it has updated after I exited this instance so I think it actually is working. Sorry for the noise!
