### ISSUE TITLE
IINACT fails to load and is marked decommissioned.

### ISSUE THREAD

**Issue by chipgeekjr** [marzent/IINACT#78]
Title, when I try to install the plugin it fails and tells me to restart my game and try again, after restart it has a load error and is marked as decommissioned.
![IINACTError](https://github.com/marzent/IINACT/assets/26667926/2664135c-7795-490b-9fad-0e0e207908d9)
Intel iMac, MacOS Sonoma 14.4.1

**Comment by natis1** [comment]
I'm having the same issue, sans the (decommissioned) text on Fedora Linux 39

![Screenshot_20240329_005410](https://github.com/marzent/IINACT/assets/2016651/eb18554c-1703-45f2-9778-54b6a1f46ee1)

**Comment by natis1** [comment]
Forcing it to Windows 7 does resolve this issue. I'm not sure how sustainable it is as a long term solution given its losing support, but for now this does work great, thanks!

**Comment by marzent** [comment]
> I'm not sure how sustainable it is as a long term solution given its losing support

With the Dalamuds update to .NET 8, Winforms started using an API that is not implemented in older Wine builds.

I do not think there is much that can be done here and if anything that is a Wine issue, which is already fixed upstream.
