### ISSUE TITLE
Requires update for 6.21

### ISSUE THREAD

**Issue by rootdarkarchon** [marzent/IINACT#8]
Title says all, currently not functioning with 6.21

**Comment by marzent** [comment]
It’s currently in a weird spot where I almost have it at a point to not require updates on game patches just like base ACT and use the plugin auto update system, but it is not *quite* there yet…

Will create a release with the current SDK after work with what is on master though.

**Comment by marzent** [comment]
In the meantime in the discord dev channel (https://discord.gg/Eqd42K53Qp) there is also a build against 2.6.6.5 beta (which will not be accepted by fflogs however)

**Comment by marzent** [comment]
Fixed with 0.2
