### ISSUE TITLE
Unable to install IINACT

### ISSUE THREAD

**Issue by jowy10** [marzent/IINACT#81]
I have been using IINACT since forever, but a while ago it just stopped working after a mandatory update. It happened around the end of February but did not bother as I temporary stopped playing

I am now back into the game and I am still unable to run it. I am using an M1 Macbook Pro 14" with XOM. I tried the "nuke" option (close XIV instances, delete IINACT folder from installedPlugins, opened XIV and attempt to install) but I keep receiving the error as shown in the screenshot.  I can see it creates the folder again and it's downloading files. 

Any idea? Do you need more information?

![Screenshot 2024-05-14 alle 02 56 01](https://github.com/marzent/IINACT/assets/69034964/0b22ce55-4953-4631-b987-55651d54b743)

**Comment by jowy10** [comment]
I checked closed issues and forced Wine to Win7 seems to works. Kinds weird since XOM is tailored for XIV use :/

**Comment by marzent** [comment]
Yeah unfortunately moving to wine 9+ was not possible for XOM yet, as it can cause random crashes from the reloaded hook backbend when interacting with the games UI.

This should hopefully be fixed with DT though.
