### ISSUE TITLE
Cactbot Raidboss overlay broken in TEA

### ISSUE THREAD

**Issue by Dormanil** [marzent/IINACT#84]
Moving over here from the Discord for there to be a more central location for responses.

I have confirmed that during the first phase of The Epic of Alexander (Ultimate), some alerts are missing (particularly for the first tankbuster and for times to move the boss), the timeline is completely gone, and during Limit Cut, at least the timeline returns to normal. I haven't checked yet how/if the ACT version of the cactbot plugin differs from the IINACT implementation during any phase past LC. 

I have confirmed that changing the overlay URL to the unproxied original does not fix the issue. There are no logs, neither in the dalamud log, nor in the web console of the overlay.

**Comment by marzent** [comment]
Should be fixed with https://github.com/marzent/IINACT/commit/c3a5cff7d1d339ec76473aa17850bf187e99e37c
