### ISSUE TITLE
Cactbot Config Proxy broken

### ISSUE THREAD

**Issue by Styr1x** [marzent/IINACT#87]
I noticed that https://proxy.iinact.com/overlay/cactbot/ui/config/config.html is not loading in BW, but https://overlayplugin.github.io/cactbot/ui/config/config.html seems to work.
Proxy does throw an error in a Desktop browser also, so it seems to be an issue not BW related.

**Comment by FleetAdmiralButter** [comment]
Hey @Styr1x, could you show me what error it's throwing when loading via the proxy? I just double checked and it appears to be loading all the resources correctly for me.

**Comment by Styr1x** [comment]
I can't reproduce it anymore, it either was a temporary error or caching related (does the proxy cache something?)
It was webpack related but didn't investigate further. I'll open a new issue should it happen again with detailed error logs.
Thanks ^^

**Comment by FleetAdmiralButter** [comment]
There are a couple layers of cache at play here - one at CloudFront and another filesystem cache at the proxy server itself. It's quite good at keeping in sync usually but if the overlay itself gets a big update things can break for a few hours until the cache expires or I manually invalidate it.
