### ISSUE TITLE
Ember Overlay not working

### ISSUE THREAD

**Issue by Troykakaa** [marzent/IINACT#89]
So I use Ember Overlay, and yesterday, it suddenly stopped working on my end. Went to see if it was a Browsingway issue, but all of the other overlays worked just fine!

**Comment by ThiconZ** [comment]
I'm running into this issue along with other users. It appears the `proxy.iinact.com/overlay/ember_overlay` was not updated with the latest version of ember overlay that's now available. Using the "official" ember overlay proxy website results in it working without any issues.

Example official proxy website path: https://goldenchrysus.github.io/ffxiv/ember-overlay/?HOST_PORT=ws://127.0.0.1:10501

@marzent can the backend version get updated please.

**Comment by Troykakaa** [comment]
> I'm running into this issue along with other users. It appears the `proxy.iinact.com/overlay/ember_overlay` was not updated with the latest version of ember overlay that's now available. Using the "official" ember overlay proxy website results in it working without any issues.
> 
> Example official proxy website path: https://goldenchrysus.github.io/ffxiv/ember-overlay/?HOST_PORT=ws://127.0.0.1:10501
> 
> @marzent can the backend version get updated please.

Thank you for this! I will use this link until the iinact version is updated.

**Comment by Kliuqard** [comment]
Hey, I just want to barge in and bump this issue, as it is still the case even now.
