### ISSUE TITLE
Can't load IINACT through Dalamund anymore

### ISSUE THREAD

**Issue by DotFlav** [marzent/IINACT#91]
I can't load IINACT with Dalamund / XIVLauncher anymore since DT release. 

If I try to load it: 
![image](https://github.com/marzent/IINACT/assets/173554147/29d5ae5d-80f4-4106-b407-80d4d5ceb584)

If I uninstall, restart and install it again:
![image](https://github.com/marzent/IINACT/assets/173554147/e14d1591-bc61-4bf9-a922-529d09ca8ba6)

I already tried to remove everything related and restart the game / computer.

**Comment by Velin92** [comment]
Same issue here, using the game with XIV on Mac, using the PC license

**Comment by Velin92** [comment]
[dalamud.log](https://github.com/user-attachments/files/16201900/dalamud.log)


These are my dalamud logs

**Comment by DotFlav** [comment]
The problem got fixed for me, without doing anything from my side. So probably solved.
