### ISSUE TITLE
[Suggestion] HP overlay for Target / Focus

### ISSUE THREAD

**Issue by Lusaca87** [marzent/IINACT#92]
Hello. I wanted to ask if it could be possible to add a the HP overlay from ACT for Target / Focus target?
See picture what i mean.
best regards
![grafik](https://github.com/marzent/IINACT/assets/17047430/3b4dc6a9-21b0-40ed-97bc-4e8e5d72c089)

**Comment by dStonecypher** [comment]
try https://github.com/Caraxi/SimpleTweaksPlugin/blob/main/Tweaks.md Target HP?
Many overlays may also provide an extra bar, or replacement bar if that's what you're looking for

IINACT is really built to only do ffxiv combat parsing things, leaving overlays, output, etc. to other tools, see https://github.com/marzent/IINACT?tab=readme-ov-file#iinact

**Comment by Lusaca87** [comment]
Thank you. The Plugin has an WS Url to so its easy, only have to install the plugin itself and bind it to the iinact ws.
