### ISSUE TITLE
Incorrect URL for Cactbot Boss Timeline

### ISSUE THREAD

**Issue by NyoroRhaeven** [marzent/IINACT#93]
The URL provided for the proxy Cactbot Boss Timeline is the same as for the Boss Alerts, the Alerts=1 and Timeline=0 in the URL need switching around

**Comment by marzent** [comment]
Hm weird, the URLs are sourced from [here](https://github.com/cking/act-overlays/blob/main/overlays.json) and there it seems to be correct.
I also cannot replicate the issue:
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/f6625027-b93d-4016-84fd-2922b8e21cca">
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/460b46c6-9e00-4d5a-b0c1-9faefd2c9804">
