### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by Linoa235** [marzent/IINACT#97]
Why does act no longer work? I no longer have the texts or the alerts, I just have the timeline? I'm going to go back to the act so it works better lol ^^

**Comment by Linoa235** [comment]
works on a shadow challenge but not in the dj 50/60 I compared with act

**Comment by marzent** [comment]
Would you mind specifying which fights exactly shadow challenge and dj 50/60 are? Is it current content?
Also keep in mind that you are comparing remote cactbot with IINACT(which might introduce bugs, but quicker updates) vs a local cactbot install with ACT.

**Comment by Linoa235** [comment]
> Would you mind specifying which fights exactly shadow challenge and dj 50/60 are? Is it current content? Also keep in mind that you are comparing remote cactbot with IINACT(which might introduce bugs, but quicker updates) vs a local cactbot install with ACT.

It's good I installed the plugins and it's good everything works again. I had the problem or in certain RAIDs the alerts did not work after the 504 problem which had

**Comment by marzent** [comment]
Ah that makes a lot sense, there were some networking issues going on for a while, glad it works now!
