### ISSUE TITLE
Cactbot not loading sometimes

### ISSUE THREAD

**Issue by DevanConradie** [marzent/IINACT#99]
Ive had an issue over the past few days where cactbot specifically the raid timelines dont load on certain fights, it is very inconsistent and i can not figure out what causes it as sometimes it loads on for example fight A and then I do the fight again and it doesnt load the following time

**Comment by marzent** [comment]
Anything in the log that stands out?
I can try to take a look, there are still some DT cactbot changes that need to go in as well...

**Comment by DevanConradie** [comment]
Im not sure about the log, the issue occurs in old content and in dawntrail stuff, Im using it through IINACT and Browsingway if that helps

**Comment by Dajova** [comment]
I can confirm it started happening recently. Sometimes it just flat out fail to load at al.
![image](https://i.imgur.com/RlTcxgZ.png)

**Comment by NotNite** [comment]
This is not a cactbot problem. WinForms is now missing from Dalamud upstream and is causing the load to fail.

**Comment by marzent** [comment]
This has been fixed in the current Dalamud version now.
